---
title: "Last Session"
author: "101401 - Asoka Niyonsaba Jean Claude"
date: "2025-10-16"
output: html_document
---

```{r}
# load dataset
data("women")

# Fit linear model
fit <- lm(weight ~ height, data = women)
summary(fit)
```
```{r}
# Weight
women$weight
```


```{r}
fitted(fit)
```
```{r}
residuals(fit)
```
```{r}
plot(women$height, women$weight, xlab="Height (in inches)", ylab="Weight (in pounds)")
abline(fit, col = "red", lwd = 2)
```

```{r}
fit2 <- lm(weight ~ height + I(height^2), data = women)
summary(fit2)
```
```{r}
plot(women$height, women$weight, xlab = "Height (in inches)", ylab = "Weight(in pounds)")
lines(women$height, fitted(fit2))
```
## By explaination "Multiple linear regression is a statistical method used to model the relationship between one dependent (response) variable and two or more independent (explanatory) variable"

```{r}
fit <- lm(weight~height,data=women)
par(mfrow=c(2,2))
plot(fit)
```
```{r}
fit2<- lm(weight~height+I(height^2), data=women)
par(mfrow=c(2,2))
plot(fit2)
```
```{r}
newfit<-lm(weight~height+I(height^2), data=women[-c(13,15),])
par(mfrow=c(2,2))
plot(newfit)
```
```{r}
plot(mpg~wt, data=mtcars)
model<- lm(mpg~wt, data=mtcars)
# plot(model)
abline(model)
```
```{r}
summary(model)
```
```{r}
predict(model, newdata=data.frame(wt=6))
```

## SIMULATION IN R
```{r}
x <- rnorm(10)
pnorm(2)
x <- rnorm(10, 20, 2)
```

```{r}
## Setting the random number seed
set.seed(1)
rnorm(5)
```
```{r}
## Always set your seed!
set.seed(1)

## Always set your seed!
set.seed(20)

## Simulate predictor variable
x <- rnorm(100)

## Simulate the error term
e <- rnorm(100, 0, 2)

## Computer the outcome via the model
y <- 0.5 - 2 * x + e

plot(x, y)
```

```{r}
set.seed(1)
sample(1:10, 4)
```
```{r}
sample(1:10,4)
```
```{r}
## Doesn't have to be numbers
sample(letters, 5)
```
```{r}
## Do a random permutation
sample(1:10)
```

```{r}
sample(1:10)
```
```{r}
## Sample w/replacement
sample(1:10, replace = TRUE)
```

