---
title: "Second Session"
author: "101401 - Asoka Niyonsaba Jean Claude"
date: "2025-10-16"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# CLASS 2 & 3:
# DATA VISUALIZATION AND DATA MANAGEMENT

```{r}

##1. Data Visualization – Bar Charts
data1 <- read.table(text="
Sept_2022 Oct_2022 Nov_2022 Dec_2022 Jan_2023 Feb_2023 Mar_2023 Apr_2023 May_2023 June_2023
1 4 6 30 140 67 47 23 39 134 80
2 10 2 29 164 72 81 28 63 211 132", header=TRUE)

barplot(as.matrix(data1),
main="Confirmed Cases vs Gender",
beside=TRUE,
col=c('gold3','red'))
legend("topright", c("Male","Female"), cex=0.8, bty="n", fill=c("gold3","red"))

##COVID-19 Tests vs Gender
data3 <- read.table(text="
sept_2022 Oct_2022 Nov_2022 Dec_2022 Jan_2023 Feb_2023 Mar_2023 Apr_2023 May_2023 June_2023
1 867 582 1802 12003 3059 9205 5346 7269 5933 3245
2 842 436 1805 11785 3508 10908 4902 7883 5901 4646", header=TRUE)

barplot(as.matrix(data3),
main="COVID-19 Tests vs Gender",
beside=TRUE,
col=c("blue","purple"))
legend("topleft", c("Male","Female"), cex=1, bty="n", fill=c("blue","purple"))


#Confirmed Cases vs Age Category
data2 <- read.table(text="
Sept_2022 Oct_2022 Nov_2022 Dec_2022 Jan_2023 Feb_2023 Mar_2023 Apr_2023 May_2023 June_2023
1 0 0 1 9 8 7 1 4 11 22
2 11 3 41 242 104 78 44 86 244 147
3 3 5 17 53 27 43 6 12 90 43", header=TRUE)

barplot(as.matrix(data2),
main="Confirmed Cases vs Age Categories",
beside=TRUE,
col=c("green","blue","purple"))
legend("topleft",
c("Less than 15 years","15–49 years","Above 50"),
cex=1, bty="n", fill=c("green","blue","purple"))

#2. Line Plot – Confirmed vs Treatment
months <- c("Sept_2022","Oct_2022","Nov_2022","Dec_2022","Jan_2023","Feb_2023","Mar_2023","Apr_2023","May_2023","June_2023")
Confirmed_covid <- c(14,8,59,304,139,128,51,102,345,212)
treatment <- c(12,0,26,217,104,57,12,47,23,20)

plot(Confirmed_covid, type="l", pch=21, col="red", ylim=c(0,350),
xaxt="n", ylab="Number of patients", main="Confirmed Cases vs Treatment")
lines(treatment, col="blue", lty=2)
legend("topleft", legend=c("Received treatment","Confirmed"), cex=0.8, fill=c("blue","red"))
axis(1, at=1:10, labels=months)

#3. Line Plot – COVID Tests
months <- c("Sept_2022","Oct_2022","Nov_2022","Dec_2022","Jan_2023","Feb_2023","Mar_2023","Apr_2023","May_2023","June_2023")
number_of_test <- c(1709,1018,3607,23788,6567,20113,10248,15152,11834,7891)

plot(number_of_test, type="o", col="blue", ylim=c(0,24000),
xaxt="n", ylab="Number of Tests", main="COVID-19 Test Trend")
axis(1, at=1:10, labels=months)

#4. ggplot2 Visualization
# install.packages("ggplot2") # run once

library(ggplot2)
data(mtcars)

barplot(table(mtcars$cyl),
main="Distribution of Car Cylinder Counts",
xlab="Number of Cylinders",
ylab="Number of Cars",
col="skyblue")

ggplot(data=mtcars, aes(x=wt, y=mpg)) +
geom_point(color="blue", size=2) +
geom_smooth(method="lm", color="green") +
labs(title="Automobile Data", x="Weight", y="Miles per Gallon")

#5. Data Management
#Combine Columns and Rows
data2 <- data.frame(x=1:3, y=c("a","b","c"))
cbind(data2, data.frame(z=3:1))
rbind(data2, data.frame(x=10, y="z"))

#6. Working with Data Frames
data_class <- data.frame(
HEIGHT=c(161,155,158,170,160),
WEIGHT=c(50,49,42,65,60)
)
BMI <- round(data_class$WEIGHT / (data_class$HEIGHT/100)^2, 1)
cbind(data_class, BMI)
summary(BMI)

#7. Subsetting and Missing Values
manager <- c(1,2,3,4,5)
country <- c("US","US","UK","UK","UK")
gender <- c("M","F","F","M","F")
age <- c(32,45,25,39,99)
q1 <- c(5,3,3,3,2)
q2 <- c(4,5,5,3,2)
q3 <- c(5,2,5,4,1)
q4 <- c(5,5,5,NA,2)
q5 <- c(5,5,2,NA,1)

leadership <- data.frame(manager,country,gender,age,q1,q2,q3,q4,q5)
leadership$age[leadership$age==99] <- NA
leadership$agecat[leadership$age>75] <- "Elder"
leadership$agecat[leadership$age>=35 & leadership$age<=75] <- "Middle Aged"
leadership$agecat[leadership$age<35] <- "Young"

leadership

#8.Using dplyr for Data Management
#install.packages("nycflights13")
#install.packages("dplyr")

library(nycflights13)
library(dplyr)

# Filter examples

jan <- filter(flights, month==1)
dec25 <- filter(flights, month==12, day==25)

# Arrange

arrange(flights, desc(arr_delay))

# Select

time_var <- select(flights, year, month, day)

# Mutate

flights2 <- select(flights, year:day, ends_with("delay"), distance, air_time)
mutate(flights2,
gain = arr_delay - dep_delay,
speed = distance / air_time * 60)
```
